import {combineReducers} from 'redux';
import counter from './counter';
// import reducers related to other features here

const rootReducer = combineReducers({
  counter //,
  // other reducers here
})
// This is the shorthand for: combineReducers({counter: counter})

export default rootReducer;

/**
 * combineReducers:
 * Arguments​:
 *   reducers (Object): An object whose values correspond to different reducing functions 
 *                      that need to be combined into one. 
 * Returns:
 *   (Function): A reducer that invokes every reducer inside the reducers object, 
 *               and constructs a state object with the same shape.
 * 
 * Passing this rootReducer to createStore, will generate a state with the structre that 
 * has the same shape with the combineReducers' argument structure here:
 * 
 * state: {
 *  counter: 0,
 *  otherReducer: otherReducer's initial state value
 * }
 * 
 * The keys in combineReducers' argument, is also the keys in store generated by createStore.
 */